definitions:
  middlewares.Error:
    properties:
      code:
        type: integer
      description:
        type: string
    type: object
  middlewares.ErrorValidation:
    properties:
      code:
        type: integer
      description:
        type: string
      validationError:
        items:
          $ref: '#/definitions/middlewares.ValidationError'
        type: array
    type: object
  middlewares.ValidationError:
    properties:
      field:
        type: string
      message:
        type: string
      path:
        type: string
      value: {}
    type: object
  request.CreateAccount:
    properties:
      document_number:
        type: string
    required:
    - document_number
    type: object
  request.CreateTransaction:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      operation_type_id:
        type: integer
    required:
    - account_id
    - amount
    - operation_type_id
    type: object
  response.Account:
    properties:
      account_id:
        type: integer
      document_number:
        type: string
    type: object
  response.Transaction:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      event_date:
        type: string
      id:
        type: integer
      operation_type_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Controle de Transação API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Controle de Transação API | Pismo
  version: "1.0"
paths:
  /v1/accounts:
    post:
      consumes:
      - application/json
      description: Create an account by given document number
      parameters:
      - description: document number for account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/request.CreateAccount'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middlewares.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/middlewares.ErrorValidation'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Error'
      summary: Create an account
  /v1/accounts/{accountId}:
    get:
      consumes:
      - application/json
      description: Create an account by given document number
      parameters:
      - description: ID account
        in: path
        name: accountId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middlewares.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middlewares.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/middlewares.ErrorValidation'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Error'
      summary: Create an account
  /v1/transaction:
    post:
      consumes:
      - application/json
      description: Create an account by given document number
      parameters:
      - description: body for create one transaction
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/request.CreateTransaction'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.Transaction'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middlewares.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/middlewares.ErrorValidation'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Error'
      summary: Create an account
schemes:
- http
swagger: "2.0"
