// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maiaaraujo5/controle-de-transacao/app/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// AccountCreator is an autogenerated mock type for the AccountCreator type
type AccountCreator struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, account
func (_m *AccountCreator) Create(ctx context.Context, account *model.Account) (*model.Account, error) {
	ret := _m.Called(ctx, account)

	var r0 *model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Account) (*model.Account, error)); ok {
		return rf(ctx, account)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Account) *model.Account); ok {
		r0 = rf(ctx, account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Account) error); ok {
		r1 = rf(ctx, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountCreator creates a new instance of AccountCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountCreator {
	mock := &AccountCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
