// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/maiaaraujo5/controle-de-transacao/app/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// AccountFinder is an autogenerated mock type for the AccountFinder type
type AccountFinder struct {
	mock.Mock
}

// Finder provides a mock function with given fields: ctx, ID
func (_m *AccountFinder) Finder(ctx context.Context, ID int64) (*model.Account, error) {
	ret := _m.Called(ctx, ID)

	var r0 *model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.Account, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.Account); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAccountFinder creates a new instance of AccountFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountFinder {
	mock := &AccountFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
